### ISSUE TITLE
Trying to install noflo-xml on Ubuntu

### ISSUE THREAD

**Issue by aniston** [noflo/noflo-xml#1]
while trying to install noflo-xml on Ubuntu, i keep getting (while doing grunt build)
Warning: failed to fetch https://raw.githubusercontent.com/noflo/noflo-xml/master/component.json, got 404 "Not Found" Use --force to continue.

As can be noted the component.json file is not there. Any solutition to get round this ?

**Comment by bergie** [comment]
noflo-xml is Node.js only, and needs to be installed via NPM
